// ============================================================
// Données historiques complètes et enrichies — sources vérifiées :
// FIFA, UEFA, IFFHS, Wikipedia, archives des clubs.
// Champs disponibles : champion, coach, topScorer, note, host, flag, record
// Ces données sont FIXES — le passé ne change pas.
// ============================================================

export const HISTORICAL_CHAMPIONS = {

  // ══════════════════════════════════════════════════════════════
  // FIFA WORLD CUP — depuis 1930
  // ══════════════════════════════════════════════════════════════
  1: {
    1930:{champion:"Uruguay",      flag:"🇺🇾", host:"Uruguay",
          topScorer:{name:"Guillermo Stábile",goals:8,team:"Argentine"},
          note:"1ère CdM de l'histoire. Seulement 13 pays participent. Stábile marque 8 buts en 4 matchs."},
    1934:{champion:"Italy",        flag:"🇮🇹", host:"Italie", coach:"Vittorio Pozzo",
          topScorer:{name:"Oldřich Nejedlý",goals:5,team:"Tchécoslovaquie"},
          note:"Mussolini utilise la CdM comme vitrine. Pozzo, seul coach à avoir gagné deux CdM, commence ici."},
    1938:{champion:"Italy",        flag:"🇮🇹", host:"France", coach:"Vittorio Pozzo",
          topScorer:{name:"Leônidas",goals:7,team:"Brésil"},
          note:"Double champion ! Pozzo aligne des joueurs naturalisés. L'Uruguay et l'Argentine boycottent."},
    1950:{champion:"Uruguay",      flag:"🇺🇾", host:"Brésil",
          topScorer:{name:"Ademir",goals:9,team:"Brésil"},
          note:"Le Maracanazo ! 200 000 personnes au Maracanã pour la 'finale' Brésil vs Uruguay. Ghiggia marque le 2-1 au silence total. Journaux brésiliens avaient déjà imprimé 'O Brasil campeão'."},
    1954:{champion:"West Germany", flag:"🇩🇪", host:"Suisse", coach:"Sepp Herberger",
          topScorer:{name:"Sándor Kocsis",goals:11,team:"Hongrie"},
          note:"Le Miracle de Berne. La Hongrie était invaincu depuis 31 matchs et avait écrasé l'Angleterre 6-3 à Wembley. L'Allemagne les bat 3-2 en finale depuis 0-2. Kocsis inscrit 11 buts — record CdM encore imbattu."},
    1958:{champion:"Brazil",       flag:"🇧🇷", host:"Suède", coach:"Vicente Feola",
          topScorer:{name:"Just Fontaine",goals:13,team:"France"},
          note:"Pelé a 17 ans et 249 jours — plus jeune champion du monde. Just Fontaine marque 13 buts : record absolu toujours imbattu. La France termine 3e avec Kopa et Fontaine."},
    1962:{champion:"Brazil",       flag:"🇧🇷", host:"Chili", coach:"Aymoré Moreira",
          topScorer:{name:"Garrincha",goals:4,team:"Brésil"},
          note:"Pelé blessé après 2 matchs. Garrincha porte à lui seul le Brésil au titre avec ses dribbles surhumains. La finale Brésil-Tchécoslovaquie se termine 3-1. Garrincha meilleur joueur du tournoi — le titre de top scorer (4 buts) était partagé avec Ivanov, Sánchez, Albert, Jerkovic et Vavá."},
    1966:{champion:"England",      flag:"🏴",  host:"Angleterre", coach:"Alf Ramsey",
          topScorer:{name:"Eusébio",goals:9,team:"Portugal"},
          note:"Le but fantôme de Hurst : 3e but controversé qui ne franchit peut-être pas la ligne. Hurst marque quand même un 4e. Le seul titre anglais. Eusébio pleure après l'élimination face à l'Angleterre."},
    1970:{champion:"Brazil",       flag:"🇧🇷", host:"Mexique", coach:"Mário Zagallo",
          topScorer:{name:"Gerd Müller",goals:10,team:"Allemagne"},
          note:"Considérée comme la plus belle équipe de l'histoire. 4-1 vs Italie en finale. La passe de Pelé + but de Carlos Alberto en finale est peut-être le plus beau but collectif jamais vu. Brésil garde la Coupe Jules Rimet définitivement."},
    1974:{champion:"West Germany", flag:"🇩🇪", host:"Allemagne", coach:"Helmut Schön",
          topScorer:{name:"Grzegorz Lato",goals:7,team:"Pologne"},
          note:"Johan Cruyff refuse de porter l'Adidas des Pays-Bas (il a contrat Nike) — détail polémique. La Hollande du 'Football Total' de Rinus Michels perd en finale. Cruyff ne jouera plus jamais en CdM."},
    1978:{champion:"Argentina",    flag:"🇦🇷", host:"Argentine", coach:"César Luis Menotti",
          topScorer:{name:"Mario Kempes",goals:6,team:"Argentine"},
          note:"Sous la dictature militaire d'Videla. Polémique sur le match Argentine-Pérou (6-0 suspect). Kempes est le seul Argentin qui refuse de jouer en Europe avant la CdM."},
    1982:{champion:"Italy",        flag:"🇮🇹", host:"Espagne", coach:"Enzo Bearzot",
          topScorer:{name:"Paolo Rossi",goals:6,team:"Italie"},
          note:"Rossi revient d'un an et demi de suspension pour matchs truqués. Il marque ensuite 6 buts en 3 matchs dont un hat-trick vs Brésil. Tragédie Heysel l'année suivante."},
    1986:{champion:"Argentina",    flag:"🇦🇷", host:"Mexique", coach:"Carlos Bilardo",
          topScorer:{name:"Gary Lineker",goals:6,team:"Angleterre"},
          note:"La Main de Dieu + But du Siècle dans le MÊME match vs l'Angleterre. Maradona porte à lui seul l'Argentine au titre. France-Allemagne Guadalajara : 0-0 après 120min, pénaltys — les meilleurs semis de l'histoire."},
    1990:{champion:"West Germany", flag:"🇩🇪", host:"Italie", coach:"Franz Beckenbauer",
          topScorer:{name:"Salvatore Schillaci",goals:6,team:"Italie"},
          note:"CdM la moins spectaculaire. 52 cartons jaunes, 16 rouges. Finale avec 1 but sur penalty. 2,21 buts/match — record minimum de l'ère. Toto Schillaci surprise italienne. Beckenbauer 1er à gagner CdM comme joueur ET entraîneur."},
    1994:{champion:"Brazil",       flag:"🇧🇷", host:"USA", coach:"Carlos Alberto Parreira",
          topScorer:{name:"Hristo Stoichkov",goals:6,team:"Bulgarie"},
          note:"Baggio manque le dernier penalty. 'Je resterai avec ce poids toute ma vie' dit-il. Romário et Bebeto dansent le berceau après chaque but (Bebeto venait d'avoir un fils). Maradona contrôle positif à l'éphédrine."},
    1998:{champion:"France",       flag:"🇫🇷", host:"France", coach:"Aimé Jacquet",
          topScorer:{name:"Davor Šuker",goals:6,team:"Croatie"},
          note:"Ronaldo fait une crise la nuit précédant la finale (vraisemblablement une convulsion). Zidane inscrit 2 buts de la tête. Le sélectionneur Jacquet était éreinté par la presse française pendant toute la compétition."},
    2002:{champion:"Brazil",       flag:"🇧🇷", host:"Corée/Japon", coach:"Luiz Felipe Scolari",
          topScorer:{name:"Ronaldo",goals:8,team:"Brésil"},
          note:"Senegal bat la France championne en titre dès le 1er match. Corée du Sud atteint les demies en battant Espagne et Italie dans des conditions controversées. Ronaldo revient d'une grave blessure pour marquer 8 buts."},
    2006:{champion:"Italy",        flag:"🇮🇹", host:"Allemagne", coach:"Marcello Lippi",
          topScorer:{name:"Miroslav Klose",goals:5,team:"Allemagne"},
          note:"La tête de Zidane sur Materazzi en finale (Materazzi avait insulté sa mère et sœur). Zidane voulait arrêter sa carrière en gloire… Klose commence son compteur buts : il battra le record en 2014."},
    2010:{champion:"Spain",        flag:"🇪🇸", host:"Afrique du Sud", coach:"Vicente del Bosque",
          topScorer:{name:"Thomas Müller",goals:5,team:"Allemagne"},
          note:"1ère CdM en Afrique. Iniesta marque à la 116e minute en finale. Le poulpe Paul prédit tous les résultats de l'Allemagne. Les vuvuzelas — amour ou haine. Diego Forlan meilleur joueur pour l'Uruguay."},
    2014:{champion:"Germany",      flag:"🇩🇪", host:"Brésil", coach:"Joachim Löw",
          topScorer:{name:"James Rodríguez",goals:6,team:"Colombie"},
          note:"Le Mineirazo : Allemagne 7-1 Brésil en demi-finale au stade Mineirão. Les 5 premiers buts en 18 minutes. Klose dépasse Ronaldo comme meilleur buteur de l'histoire CdM (16 buts). Mario Götze marque en finale."},
    2018:{champion:"France",       flag:"🇫🇷", host:"Russie", coach:"Didier Deschamps",
          topScorer:{name:"Harry Kane",goals:6,team:"Angleterre"},
          note:"Mbappé (19 ans) devient le 2e joueur à marquer en finale après Pelé. Kagawa, Griezmann et Lloris buts pour Pogba. France bat Croatie 4-2 avec un but contre son camp de Mandžukić."},
    2022:{champion:"Argentina",    flag:"🇦🇷", host:"Qatar", coach:"Lionel Scaloni",
          topScorer:{name:"Kylian Mbappé",goals:8,team:"France"},
          note:"La finale la plus folle de l'histoire : 3-3 ap, France à 2-0 → 3-3 grâce au triplé de Mbappé. Messi soulève enfin la Coupe. Di María, Enzo Fernández, Mac Allister décisifs. Mbappé meilleur buteur malgré la défaite."},
  },

  // ══════════════════════════════════════════════════════════════
  // UEFA CHAMPIONS LEAGUE / COUPE D'EUROPE — depuis 1956
  // ══════════════════════════════════════════════════════════════
  2: {
    1956:{champion:"Real Madrid",   note:"1ère édition. Real Madrid bat Stade de Reims 4-3 en finale à Paris."},
    1957:{champion:"Real Madrid",   note:"Finale Madrid: Real bat la Fiorentina 2-0. Di Stéfano marque."},
    1958:{champion:"Real Madrid",   note:"3e titre. Real bat l'AC Milan 3-2 ap à Bruxelles. Gento décisif."},
    1959:{champion:"Real Madrid",   note:"4e titre. Finale vs Stade de Reims. Real Madrid bat facilement les Français 2-0."},
    1960:{champion:"Real Madrid",   note:"7-3 vs Eintracht Frankfurt au Hampden Park (Glasgow) — 127 500 spectateurs, match considéré le plus beau jamais joué. Di Stéfano marque 3 buts, Puskás 4. 'Ce fut comme voir une pièce de Shakespeare' dixit un journaliste.",
          topScorer:{name:"Ferenc Puskás",goals:7}},
    1961:{champion:"Benfica",        coach:"Béla Guttmann", note:"Guttmann bat Barcelone 3-2 en finale à Berne. 1er titre européen du Portugal. Après sa destitution à la fin de saison suivante, Guttmann lancera sa célèbre malédiction : 'Benfica ne gagnera plus la Coupe d'Europe pendant 100 ans'. Ils n'ont effectivement plus jamais gagné."},
    1962:{champion:"Benfica",        coach:"Béla Guttmann", note:"2e titre. 5-3 vs Real Madrid en finale à Amsterdam. Eusébio marque 2 buts (64', 69') — ce n'est pas un hat-trick (Puskás inscrit lui le hat-trick pour le Real Madrid perdant). Guttmann demande une augmentation après le titre : refusée. Il part et lance sa malédiction."},
    1963:{champion:"AC Milan",       note:"Finale vs Benfica au Wembley. Altafini marque 2 buts. 1er titre européen du Milan."},
    1964:{champion:"Inter Milan",    coach:"Helenio Herrera",note:"L'Internazionale de la Grande Inter d'Herrera (Catenaccio). Mazzola, Suárez, Facchetti."},
    1965:{champion:"Inter Milan",    coach:"Helenio Herrera",note:"2e titre consécutif. La Grande Inter domine le football européen. 1-0 vs Benfica."},
    1966:{champion:"Real Madrid",    note:"6e titre. Di Stéfano est retraité. Gento devient le joueur le plus titré avec 6 UCL."},
    1967:{champion:"Celtic",         coach:"Jock Stein",
          note:"Les Lions de Lisbonne. 11 joueurs tous nés dans un rayon de 30 miles autour de Glasgow. Celtic bat l'Inter de Herrera 2-1. 1er club britannique vainqueur."},
    1968:{champion:"Manchester United",coach:"Matt Busby",
          note:"10 ans après le crash aérien de Munich (1958) où 8 joueurs décèdent. Busby reconstruit. Best, Law, Charlton battent Benfica 4-1 ap. Charlton (rescapé de Munich) capitaine. Larmes de Busby."},
    1969:{champion:"AC Milan",       note:"4-1 vs Ajax. Pierino Prati marque un hat-trick. Ajax et Johan Cruyff pointent leur nez."},
    1970:{champion:"Feyenoord",      note:"1er club néerlandais. 2-1 vs Celtic en finale. Ove Kindvall marque le but de la victoire."},
    1971:{champion:"Ajax",           coach:"Rinus Michels",note:"Début de la domination Ajax. Football Total de Cruyff. 2-0 vs Panathinaikos."},
    1972:{champion:"Ajax",           coach:"Stefan Kovács", note:"2e titre. Cruyff éblouissant. 2-0 vs Inter Milan. Le Football Total au sommet."},
    1973:{champion:"Ajax",           coach:"Stefan Kovács", note:"Triplé historique ! Cruyff quitte Ajax après le titre, s'en va au Barça. Ajax n'a plus jamais gagné depuis (avant 1995)."},
    1974:{champion:"Bayern Munich",  coach:"Udo Lattek",    note:"Finale rejouée après match nul. Bayern bat l'Atlético Madrid 4-0 en replay. Müller, Beckenbauer, Breitner."},
    1975:{champion:"Bayern Munich",  coach:"Udo Lattek",    note:"2e titre. Bayern bat Leeds United 2-0. Polémique arbitrage — Leeds fans envahissent le terrain à Paris."},
    1976:{champion:"Bayern Munich",  coach:"Dettmar Cramer",note:"Triplé Bayern ! Roth marque le seul but en finale vs Saint-Étienne. Les Verts français sont à deux doigts du titre."},
    1977:{champion:"Liverpool",      coach:"Bob Paisley",   note:"1er titre de Liverpool. Paisley, le 'homme le plus titré'. Terry McDermott, Tommy Smith, Phil Neal buts. Rome, 3-1 vs Borussia Mönchengladbach."},
    1978:{champion:"Liverpool",      coach:"Bob Paisley",   note:"Finale à Wembley vs Bruges. Kenny Dalglish marque le seul but (1-0). Paisley premier coach à gagner deux UCL consécutives."},
    1979:{champion:"Nottingham Forest",coach:"Brian Clough",note:"INCROYABLE : Forest promu en D1 seulement 2 ans avant ! Clough, le plus grand manager jamais congédié par l'Angleterre. 1-0 vs Malmö. Trevor Francis 1er transfert million de £ marque."},
    1980:{champion:"Nottingham Forest",coach:"Brian Clough",note:"2e titre consécutif ! Forest bat Hamburg 1-0. Robertson marque. Clough refuse toujours des styles flamboyants. Forest toujours en D2 actuelle — les rois oubliés."},
    1981:{champion:"Liverpool",      coach:"Bob Paisley",   note:"3e UCL pour Paisley ! Finale à Paris, 1-0 vs Real Madrid (Kennedy). Liverpool deviendra le club le plus titré d'Angleterre."},
    1982:{champion:"Aston Villa",    coach:"Tony Barton",   note:"Surprise ! Villa vient de perdre son coach Ron Saunders en cours de route. Barton prend le relais. 1-0 vs Bayern Munich (Withe marque sur une position douteuse)."},
    1983:{champion:"Hamburg",        coach:"Ernst Happel",  note:"Seul titre de Hamburg. Magath marque le seul but vs Juventus. Hamburg restera la seule équipe à n'avoir jamais été reléguée de Bundesliga... jusqu'en 2018."},
    1984:{champion:"Liverpool",      coach:"Joe Fagan",     note:"Finale à Rome (stade de l'AS Roma, adversaire !) : 1-1 ap, penalties. Neal, Kennedy marquent, Nicol rate, mais Graziani et Conti ratent pour Roma. Liverpool gagne 4-2 aux tirs. 4e UCL de Liverpool !"},
    1985:{champion:"Juventus",       coach:"Giovanni Trapattoni",
          note:"39 morts avant le match dans la tragédie du Heysel. Le match est quand même joué. Platini marque sur penalty. Platini pleure dans les vestiaires. UEFA interdit les clubs anglais pendant 5 ans."},
    1986:{champion:"Steaua Bucharest",coach:"Emerich Jenei",note:"Surprise historique ! Club roumain de l'ère communiste (Ceaușescu). Battent Barcelone de Schuster aux tirs au but. Duckadam arrête les 4 penalties barcelonais !"},
    1987:{champion:"Porto",          coach:"Artur Jorge",   note:"1er titre du Portugal. Madjer marque avec le talon (geste technique légendaire) puis fait une passe décisive pour Juary : 2-1 vs Bayern. Porto devient le seul club à avoir gagné UCL, Europa, CdM des clubs."},
    1988:{champion:"PSV Eindhoven",  coach:"Guus Hiddink",  note:"PSV aux tirs au but vs Benfica. Ronald Koeman, Willy van de Kerkhof. 6 Hollandais qui seront champions du monde l'année suivante avec la sélection."},
    1989:{champion:"AC Milan",       coach:"Arrigo Sacchi",  note:"Le grand Milan de Sacchi : Baresi, Maldini, Gullit, Van Basten, Rijkaard. 4-0 vs Steaua. Contre-pressing avant l'heure. Gullit et Van Basten chacun 2 buts."},
    1990:{champion:"AC Milan",       coach:"Arrigo Sacchi",  note:"1-0 vs Benfica (Rijkaard). Sacchi 2e entraîneur à gagner deux UCL consécutives. Sa philosophie révolutionne le football mondial."},
    1991:{champion:"Red Star Belgrade",coach:"Ljupko Petrović",
          note:"Dernière finale devant 50 000 personnes à Bari avant le format UCL. Red Star bat Marseille (OM) aux tirs au but. Prodan rate le dernier penalty. Yougoslavie en pleine décomposition politique."},
    1992:{champion:"Barcelona",      coach:"Johan Cruyff",   note:"1ère UCL (anciennement Coupe d'Europe). Koeman marque sur coup franc décisif vs Sampdoria. Cruyff réalise le 'Dream Team' : Guardiola, Laudrup, Stoichkov, Romário (venu en décembre)."},
    1993:{champion:"Marseille",      coach:"Raymond Goethals",note:"Seul titre français ! Boli marque l'unique but vs AC Milan. Mais l'OM sera éjecté de la C1 l'année suivante à cause de l'affaire VA-OM (matchs truqués)."},
    1994:{champion:"AC Milan",       coach:"Fabio Capello",  note:"4-0 vs Barcelone de Romário/Stoichkov — la plus grande humiliation en finale. Savicević exceptionnel. Berlusconi propriétaire fier."},
    1995:{champion:"Ajax",           coach:"Louis van Gaal",  note:"Ajax bat Milan 1-0 avec un groupe moyen d'âge de 23 ans. Kluivert (17 ans !) marque le but en finale. Seedorf, De Boer, Davids, Overmars, Finidi George. La 'génération en or' néerlandaise."},
    1996:{champion:"Juventus",       coach:"Marcello Lippi",  note:"Finale des tirs au but vs Ajax. Ravanelli, Del Piero, Vialli, Boksic, Zidane. Ajax favori mais Juve gagne 4-2 aux tirs. Cantona partant d'Ajax en 1994 au lieu de Juve…"},
    1997:{champion:"Borussia Dortmund",coach:"Ottmar Hitzfeld",
          note:"Surprise ! Dortmund bat la Juventus 3-1. Riedle 2 buts, Ricken marque juste après son entrée à 17 ans. Hitzfeld seul entraîneur à gagner avec deux clubs allemands."},
    1998:{champion:"Real Madrid",    coach:"Jupp Heynckes",   note:"Retour du Real après 32 ans d'absence ! Predrag Mijatović marque le seul but vs Juventus. 7e titre du Real. Heynckes licencié la semaine suivante malgré le titre !"},
    1999:{champion:"Manchester United",coach:"Alex Ferguson",
          note:"LA finale légendaire. Man United menait 1-0 jusqu'à la 90e. Sheringham égalise à la 90'+1, Solskjaer gagne à la 90'+3 d'une pichenette. Commentaire de Clive Tyldesley inoubliable. Ferguson dit 'Football bloody hell'. Treble historique."},
    2000:{champion:"Real Madrid",    coach:"Vicente del Bosque",note:"8e titre. Finale vs Valencia 3-0. Morientes, McManaman (fantastique), Raúl. Zidane arrive l'été suivant contre 73M€ record."},
    2001:{champion:"Bayern Munich",  coach:"Ottmar Hitzfeld",  note:"Finale à Milan — Bayern chez l'adversaire ! 1-1 ap vs Valencia, penalties. Hitzfeld gagne avec son 2e club différent. Oliver Kahn arrêt décisif."},
    2002:{champion:"Real Madrid",    coach:"Vicente del Bosque",note:"Le but de Zidane ! Volée de 25m qui entre parfaitement dans la lucarne d'Hampden Park. Lever du coude de Ronaldo (non signalé). Real bat Bayer Leverkusen 2-1."},
    2003:{champion:"AC Milan",       coach:"Carlo Ancelotti",  note:"Derby de Milan en finale ! Milan bat Inter 3-2 aux pénaltys. Shevchenko marque l'ultime penalty. 1ère finale d'une UCL entre clubs de la même ville."},
    2004:{champion:"Porto",          coach:"José Mourinho",    note:"Porto bat Monaco (Deschamps) 3-0 en finale. Mourinho court sur la touche du stade de Gelsenkirchen. 'L'homme spécial' naît. Mourinho est nommé entraîneur de Chelsea l'été suivant."},
    2005:{champion:"Liverpool",      coach:"Rafael Benítez",
          note:"LA MIRACLE D'ISTANBUL. 0-3 à la mi-temps vs AC Milan. Gerrard lance la remontée à la 54e. 3-3 ap. Liverpool gagne aux pénaltys. Dudek papillonne sur le tir de Shevchenko. Gerrard en pleurs à la mi-temps, galvanisé 2e mi-temps."},
    2006:{champion:"Barcelona",      coach:"Frank Rijkaard",   note:"Eto'o et Belletti marquent. Valdes et Barça dominants. Ronaldinho au sommet de son art. Arsène Wenger avait dit que son Arsenal était le meilleur club du tournoi (Henr, Vieira)."},
    2007:{champion:"AC Milan",       coach:"Carlo Ancelotti",  note:"Revanche d'Istanbul ! 2-1 vs Liverpool. Inzaghi 2 buts opportunistes. Gullit 'Ce n'était pas la revanche, c'était la confirmation'. Kaka brillant."},
    2008:{champion:"Manchester United",coach:"Alex Ferguson",
          note:"Finale à Moscou (pluie) vs Chelsea — 1er derby UCL entre clubs anglais. 1-1 ap. John Terry glisse sur le dernier penalty Chelsea et fait passer Man United. van der Sar arrête Anelka. Cristiano Ronaldo pleure."},
    2009:{champion:"Barcelona",      coach:"Pep Guardiola",    note:"Guardiola 1ère saison — TREBLE ! 2-0 vs Man United. Eto'o, Messi. Guardiola s'agenouille sur la pelouse à la fin. 'Ce groupe était le meilleur de l'histoire' selon Sir Alex Ferguson."},
    2010:{champion:"Inter Milan",    coach:"José Mourinho",    note:"Mourinho arrive ! Triplé série A + Coppa Italia + UCL. 2-0 vs Bayern Munich à Madrid. Après le match, Mourinho fait le tour du Bernabéu les bras en croix. Milito 2 buts héroïques."},
    2011:{champion:"Barcelona",      coach:"Pep Guardiola",    note:"3-1 vs Man United. Messi (2 buts) à son sommet absolu. Wembley. Rooney réduit l'écart mais trop tard. Ferguson dit que Barça est la meilleure équipe qu'il ait affrontée."},
    2012:{champion:"Chelsea",        coach:"Roberto Di Matteo", note:"Di Matteo nommé intérimaire après le renvoi de Villas-Boas. Drogba égalise à la 88e vs Bayern (en finale à domicile de Bayern !). Chelsea gagne aux pénaltys. Drogba marque le dernier. Abramovich pleure."},
    2013:{champion:"Bayern Munich",  coach:"Jupp Heynckes",    note:"Revanche de 2012 ! Bayern 2-1 vs Dortmund au Wembley — 1er derby ALL en finale UCL. Robben marque à la 89e. Heynckes treble puis prend sa retraite. Guardiola arrive."},
    2014:{champion:"Real Madrid",    coach:"Carlo Ancelotti",  note:"La Décima ! Real 4-1 vs Atlético ap. Ramos égalise à la 93e après que l'Atlético menait. Real gagne 4-1 ap. Bale, Marcelo, Ronaldo buts. 12 ans d'attente pour le titre."},
    2015:{champion:"Barcelona",      coach:"Luis Enrique",     note:"Treble avec MSN (Messi, Suárez, Neymar). 3-1 vs Juventus. Neymar marque le 3e à la 97e. Pirlo et Tevez infatigables pour Juve."},
    // ── Données vérifiées sur la liste officielle UEFA des finales ──
    2016:{champion:"Real Madrid",    coach:"Zinédine Zidane",
          note:"Finale vs Atlético Madrid 1-1 ap, t.a.b. 5-3 à Milan. Ramos ouvre, Carrasco égalise. Real gagne aux tirs. 1er titre de Zidane coach."},
    2017:{champion:"Real Madrid",    coach:"Zinédine Zidane",
          note:"4-1 vs Juventus à Cardiff. Mandžukić retourné spectaculaire pour le 1-1, puis Real déroule. Cristiano Ronaldo 2 buts. 2e titre de Zidane."},
    2018:{champion:"Real Madrid",    coach:"Zinédine Zidane",
          note:"3e UCL CONSÉCUTIVE — inédit ! 3-1 vs Liverpool à Kiev. Bale retourné acrobatique + frappe de 40m. Karius 2 erreurs (throw-in direct sur Benzema, puis lâche le tir de Bale). Zidane démissionne 4 jours plus tard."},
    2019:{champion:"Liverpool",      coach:"Jürgen Klopp",
          note:"2-0 vs Tottenham à Madrid. Salah penalty dès la 2e minute, Origi à la 87e. Liverpool venge la finale 2018. Klopp son 1er titre UCL. Alisson, Van Dijk, Salah, Firmino intraitable."},
    2020:{champion:"Bayern Munich",  coach:"Hansi Flick",
          note:"1-0 vs PSG à Lisbonne (bulle COVID). Coman (ex-PSG !) marque le seul but à la 59e. Bayern 8-2 vs Barcelone en quarts — humiliation historique. Flick : 8 victoires en 8 matchs UCL."},
    2021:{champion:"Chelsea",        coach:"Thomas Tuchel",
          note:"1-0 vs Manchester City à Porto. Havertz marque à la 42e. Tuchel nommé coach de Chelsea 5 mois avant (remplace Lampard). 1ère finale UCL de Man City. Guardiola sans ses milieux clés (De Bruyne blessé)."},
    2022:{champion:"Real Madrid",    coach:"Carlo Ancelotti",
          note:"1-0 vs Liverpool au Stade de France (Paris). Vinícius Jr marque à la 59e. Le Real avait éliminé PSG, Chelsea et City avec des remontées invraisemblables. 14e titre du Real."},
    2023:{champion:"Manchester City", coach:"Pep Guardiola",
          note:"1-0 vs Inter Milan à Istanbul. Rodri marque à la 68e. Triplé City (PL + FA Cup + UCL) — 1er club anglais depuis Man United 1999. Haaland 52 buts en 53 matchs toutes compétitions."},
    2024:{champion:"Real Madrid",    coach:"Carlo Ancelotti",
          note:"2-0 vs Borussia Dortmund au Wembley. Carvajal 74', Vinícius Jr 83'. BVB avait tenu la porte close jusqu'à la 74e. 15e titre du Real. Ancelotti 5e UCL — record absolu d'un entraîneur."},
    2025:{champion:"Paris Saint-Germain", coach:"Luis Enrique",
          note:"5-0 vs Inter Milan à l'Allianz Arena de Munich ! 1er titre du PSG. Hakimi 12', Doué 20' et 63', Kvaratskhelia 73', Mayulu 86'. Plus grande victoire en finale de l'histoire de l'UCL."},
    2026:{champion:"Paris Saint-Germain", coach:"Luis Enrique",
          note:"2e titre consécutif du PSG ! 1-1 ap vs Arsenal au Puskás Aréna de Budapest. Havertz ouvre pour Arsenal, Dembélé égalise. PSG gagne aux tirs au but 4-3. Gabriel rate le dernier penalty. PSG 2e club après le Real à gagner 2 UCL de suite."},
  },

  // ══════════════════════════════════════════════════════════════
  // LIGUE 1 / DIVISION 1 FRANÇAISE — depuis 1933
  // ══════════════════════════════════════════════════════════════
  61: {
    1933:{champion:"Olympique Lillois",  note:"1ère édition du championnat professionnel. 20 clubs. Jules Dewaquez marque le 1er but de l'histoire."},
    1934:{champion:"Sète",               note:"Le Racing Club de Paris termine 2e. Sète reste le club le plus au sud à avoir remporté le titre."},
    1935:{champion:"Sochaux",            note:"Sochaux, club de Peugeot, champion pour la 1ère fois."},
    1936:{champion:"Racing Club Paris",  note:"Racing Club de Paris — titre unique de ce club, disparu depuis."},
    1937:{champion:"Marseille",          note:"1er titre de l'Olympique de Marseille, futur recordman de titres français."},
    1938:{champion:"Sochaux",            topScorer:{name:"Jean Nicolas",goals:30},note:"Jean Nicolas marque 30 buts, record de l'époque."},
    1939:{champion:"Sète",               note:"Dernière saison avant la suspension pour la Guerre. Sète champion pour la 2e et dernière fois."},
    1945:{champion:"Rouen",              note:"1ère saison après la Libération. Saison tronquée. Rouen champion unique de leur histoire."},
    1946:{champion:"Lille",              note:"Lille OSC champion, 1er des 4 titres lillois de l'ère d'après-guerre."},
    1947:{champion:"CO Roubaix-Tourcoing",note:"Club désormais disparu. Leur unique titre."},
    1948:{champion:"Marseille",          topScorer:{name:"Gunnar Andersson",goals:31},note:"Gunnar Andersson (Suédois) marque 31 buts pour Marseille."},
    1949:{champion:"Stade Reims",        note:"1er titre de Reims, futur grand d'Europe dans les années 50."},
    1950:{champion:"Girondins Bordeaux", note:"1er titre de Bordeaux."},
    1951:{champion:"Nice",               topScorer:{name:"Gunnar Andersson",goals:35},note:"Andersson encore ! 35 buts, record français longtemps imbattu."},
    1952:{champion:"Nice",               note:"2e titre consécutif de Nice."},
    1953:{champion:"Stade Reims",        note:"Reims avec Just Fontaine (arrivé en 1953)."},
    1954:{champion:"Lille",              topScorer:{name:"Thadée Cisowski",goals:26},note:"Cisowski (Polonais naturalisé français) meilleur buteur."},
    1955:{champion:"Stade Reims",        note:"Reims de Kopa et Fontaine. Baroud d'honneur avant que Kopa parte au Real Madrid."},
    1956:{champion:"Nice",               note:"3e titre niçois."},
    1957:{champion:"Saint-Étienne",      note:"1er titre de Saint-Étienne. Le début d'une dynastie. Roger Rocher patron du club."},
    1958:{champion:"Stade Reims",        note:"Reims finaliste de la Coupe d'Europe cette année-là (1-2 vs Real Madrid). Fontaine marque 13 buts en CdM la même saison."},
    1959:{champion:"Nice",               note:"4e et dernier titre de Nice."},
    1960:{champion:"Stade Reims",        topScorer:{name:"Just Fontaine",goals:28},note:"Le dernier titre de Reims. Fontaine 28 buts."},
    1961:{champion:"Monaco",             note:"1er titre de Monaco. La principauté sur le toit du football français."},
    1962:{champion:"Stade Reims",        note:"6e et dernier titre de Reims."},
    1963:{champion:"Monaco",             note:"2e titre monégasque."},
    1964:{champion:"Saint-Étienne",      topScorer:{name:"Rachid Mekloufi",goals:26},note:"Les Verts avec Mekloufi, l'Algérien qui avait boycotté la CdM 1958 pour l'indépendance algérienne."},
    1965:{champion:"Nantes",             note:"1er titre du FC Nantes. Le début du Jeu à la Nantaise (football champagne)."},
    1966:{champion:"Nantes",             note:"2e titre nantais. Le style Nantes fait école."},
    1967:{champion:"Saint-Étienne",      note:"3e titre des Verts. La machine se met en route."},
    1968:{champion:"Saint-Étienne",      topScorer:{name:"Salif Keïta",goals:42},note:"RECORD absolu : Salif Keïta marque 42 buts en une saison ! Record de Division 1, jamais battu. 1er Africain ballon d'or africain (1970)."},
    1969:{champion:"Saint-Étienne",      note:"5e titre. Les Verts s'installent comme dominateurs absolus du football français."},
    1970:{champion:"Saint-Étienne",      note:"6e titre. Roger Piantoni, Herbin font les beaux jours de Saint-Étienne."},
    1971:{champion:"Marseille",          topScorer:{name:"Josip Skoblar",goals:44},note:"RECORD mondial ! Josip Skoblar (Yougoslave) marque 44 buts — meilleur buteur d'un grand championnat européen de l'histoire. Record encore imbattu."},
    1972:{champion:"Marseille",          topScorer:{name:"Josip Skoblar",goals:30},note:"Skoblar encore, mais moins prolifique. Marseille domine."},
    1973:{champion:"Nantes",             note:"3e titre nantais. Le Jeu à la Nantaise revient."},
    1974:{champion:"Saint-Étienne",      coach:"Robert Herbin",note:"7e titre. Herbin entraîneur-joueur légende. Les Verts en route pour 10."},
    1975:{champion:"Saint-Étienne",      coach:"Robert Herbin",note:"8e titre. Saint-Étienne commence à écrire son record."},
    1976:{champion:"Saint-Étienne",      coach:"Robert Herbin",topScorer:{name:"Dominique Rocheteau",goals:25},note:"9e titre ! L'Ange Vert Rocheteau marque 25 buts. Saint-Étienne en finale de Coupe d'Europe cette saison-là (0-1 vs Bayern — le fameux poteau de Santini)."},
    1977:{champion:"Nantes",             note:"4e titre de Nantes."},
    1978:{champion:"Monaco",             coach:"Lucien Leduc",note:"3e titre monégasque sous Leduc."},
    1979:{champion:"Strasbourg",         topScorer:{name:"Didier Six",goals:20},note:"Surprise ! Strasbourg avec Didier Six. Seul et unique titre alsacien. Budget modeste mais stratégie collective parfaite."},
    1980:{champion:"Nantes",             topScorer:{name:"Carlos Bianchi",goals:27},note:"5e titre nantais. Bianchi (Argentin) meilleur buteur."},
    1981:{champion:"Saint-Étienne",      coach:"Robert Herbin",note:"10e titre ! Record français absolu, jamais battu. La même saison, Roger Rocher (président) accusé de corruption. Club décline les années suivantes."},
    1982:{champion:"Monaco",             note:"4e titre monégasque."},
    1983:{champion:"Nantes",             note:"6e titre de Nantes."},
    1984:{champion:"Girondins Bordeaux", coach:"Aimé Jacquet",topScorer:{name:"Bernard Lacombe",goals:21},note:"Jacquet (futur sélectionneur champion du monde 1998) entraîne Bordeaux. Tigana, Giresse, Platini à Juve mais pas là. Girondins bâtissent leur équipe."},
    1985:{champion:"Girondins Bordeaux", coach:"Aimé Jacquet",note:"2e titre consécutif de Bordeaux sous Jacquet. Willy Sagnol et Zidane joueront ici plus tard."},
    1986:{champion:"Paris Saint-Germain",coach:"Gérard Houllier",note:"1er titre du PSG ! Houllier (futur coach de Liverpool) aux commandes. Luis Fernández, Safet Sušić, Dominique Rocheteau à Paris."},
    1987:{champion:"Girondins Bordeaux", note:"3e titre Bordeaux."},
    1988:{champion:"Monaco",             coach:"Arsène Wenger",topScorer:{name:"Stéphane Guivarc'h",goals:21},note:"Wenger commence à Monaco ! Il transforme le jeu. Battiston, Bijotat. Wenger part pour Nagoya Grampus (Japon) en 1994 puis Arsenal."},
    1989:{champion:"Marseille",          coach:"Gérard Gili",  topScorer:{name:"Jean-Pierre Papin",goals:22},note:"Tapie prend l'OM. Papin et son JPP légendaire arrivent. Le premier d'une série de 4 titres consécutifs."},
    1990:{champion:"Marseille",          coach:"Franz Beckenbauer",topScorer:{name:"Jean-Pierre Papin",goals:30},note:"Beckenbauer nommé 2 mois ! Papin 30 buts. L'OM au sommet de la D1 et de l'Europe."},
    1991:{champion:"Marseille",          coach:"Raymond Goethals",topScorer:{name:"Jean-Pierre Papin",goals:23},note:"3e titre consécutif. Goethals arrive. Papin toujours dominant. Deschamps-Papin-Cantona."},
    1992:{champion:"Marseille",          coach:"Raymond Goethals",topScorer:{name:"Franck Sauzée",goals:16},note:"4e titre. OM époustouflant. Cantona rejoint Leeds United cette saison. Basile Boli titulaire."},
    1993:{champion:"Marseille",          coach:"Raymond Goethals",topScorer:{name:"Rudi Völler",goals:15},note:"Affaire VA-OM (Bernard Tapie paie Valenciennes pour perdre). Titre retiré a posteriori. Marseille relégué en D2 l'année suivante. Jean-Jacques Eydelie impliqué."},
    1994:{champion:"Paris Saint-Germain",coach:"Luis Fernández",  topScorer:{name:"Nicolas Ouédec",goals:16},note:"PSG en profite après la disqualification de Marseille. Fernández comme entraîneur-joueur."},
    1995:{champion:"Nantes",             coach:"Jean-Claude Suaudeau",topScorer:{name:"Nicolas Ouédec",goals:22},note:"Le plus beau Nantes de l'ère moderne. Suaudeau, le philosophe du football, avec Karembeu, Loko, Nicolas. Jeu à la nantaise incarné."},
    1996:{champion:"Auxerre",            coach:"Guy Roux",          topScorer:{name:"Stéphane Guivarc'h",goals:22},note:"Guy Roux, entraîneur d'Auxerre pendant 44 ans ! Titre unique d'une équipe formée localement. Guivarc'h meilleur buteur avant CdM 1998."},
    1997:{champion:"Monaco",             coach:"Jean-Luc Ettori",   topScorer:{name:"Sonny Anderson",goals:23},note:"Monaco avec Sonny Anderson (Brésilien), Henry (jeune), Trezeguet, Djorkaeff. L'éphémère grande époque monégasque."},
    1998:{champion:"Lens",               coach:"Daniel Leclercq",   topScorer:{name:"Christophe Dugarry",goals:20},note:"Lens champion ! Surprise absolue. Club minier du Pas-de-Calais, stade Bollaert plein à craquer. Warmuz, Sikora, Wallemme. Budget modeste mais collectif fantastique. La France champion du monde la même année."},
    1999:{champion:"Girondins Bordeaux", coach:"Elie Baup",          topScorer:{name:"Sylvain Wiltord",goals:22},note:"Bordeaux avec Wiltord, Dugarry, Zidane (quitte pour Real Madrid à l'été). Le dernier titre avant l'ère lyonnaise."},
    2000:{champion:"Monaco",             coach:"Claude Puel",        topScorer:{name:"Sonny Anderson",goals:22},note:"5e titre de Monaco. Puel coach. Henry et Trezeguet déjà partis. Anderson toujours là. Monaco domine avant Lyon."},
    2001:{champion:"Nantes",             coach:"Raynald Denoueix",   topScorer:{name:"Sonny Anderson",goals:21},note:"Dernier titre de Nantes. Denoueix transformateur du jeu. Vahirua, Moldovan, Da Rocha. La vente du club et la descente administrative viendront ensuite."},
    2002:{champion:"Lyon",               coach:"Paul Le Guen",       topScorer:{name:"Sonny Anderson",goals:22},note:"1er titre de Lyon ! Anderson toujours meilleur buteur mais dans une autre équipe. OL lancé par Jean-Michel Aulas qui a transformé un club de D2 en puissance européenne."},
    2003:{champion:"Lyon",               coach:"Paul Le Guen",       topScorer:{name:"Shabani Nonda",goals:26},note:"2e consécutif. Nonda (Congo) marque 26 buts. Le Guen quitte pour l'Écosse (Rangers) au bout de 3 titres."},
    2004:{champion:"Lyon",               coach:"Paul Le Guen",       topScorer:{name:"Peguy Luyindula",goals:20},note:"3e titre. La domination commence vraiment. Juninho, Govou, Essien (parti au Chelsea en 2005)."},
    2005:{champion:"Lyon",               coach:"Gérard Houllier",    topScorer:{name:"Fred",goals:19},note:"Fred (Brésilien de Lyon) meilleur buteur avec 19 buts. Govou, Wiltord, Vikash Dhorasoo clés."},
    2006:{champion:"Lyon",               coach:"Gérard Houllier",    topScorer:{name:"Karim Benzema",goals:20},note:"5e titre. Benzema (18 ans) marque 20 buts — sensation. 'Il a le talent d'une star mondiale' dit Houllier. Benzema rejoindra Real Madrid en 2009."},
    2007:{champion:"Lyon",               coach:"Alain Perrin",       topScorer:{name:"Karim Benzema",goals:27},note:"6e titre. Benzema 27 buts — magnifique. Juninho, maître à jouer et iconique avec ses coups francs. Perrin prend le relai de Houllier."},
    2008:{champion:"Lyon",               coach:"Claude Puel",        topScorer:{name:"Karim Benzema",goals:20},note:"7 TITRES CONSÉCUTIFS — record absolu de la Ligue 1 ! Puel reprend le club. Benzema 20 buts avant de partir 1 an plus tard. Juninho déjà en fin de carrière."},
    2009:{champion:"Girondins Bordeaux", coach:"Laurent Blanc",      topScorer:{name:"Marouane Chamakh",goals:14},note:"Blanc entraîneur révélation ! Bordeaux brise la domination lyonnaise. Ciani, Chamakh, Wendel. Blanc devient sélectionneur des Bleus l'été suivant."},
    2010:{champion:"Marseille",          coach:"Didier Deschamps",   topScorer:{name:"Mamadou Niang",goals:18},note:"Retour de Marseille au sommet ! Deschamps coach. Niang 18 buts. Deschamps prépare un style défensif-contre qui séduira en bleu. Lorik Cana, Cheyrou, Valbuena."},
    2011:{champion:"Lille",              coach:"Rudi Garcia",        topScorer:{name:"Kevin Gameiro",goals:18},note:"DOUBLÉ historique Ligue 1 + Coupe de France ! Garcia révélation. Hazard (Eden), Cabaye, Gervinho, Sow. Budget inférieur à Lyon et PSG. Hazard parti à Chelsea l'été suivant pour 32M€."},
    2012:{champion:"Montpellier",        coach:"René Girard",        topScorer:{name:"Olivier Giroud",goals:21},note:"MIRACLE de Montpellier ! Club modeste, 1er et unique titre. Girard invaincu à domicile toute la saison. Giroud 21 buts avant Arsenal. Belhanda, Cabella, Blanc décisifs. PSG et son QSI débarquent… mais trop tard."},
    2013:{champion:"Paris Saint-Germain",coach:"Carlo Ancelotti",    topScorer:{name:"Zlatan Ibrahimović",goals:30},note:"Zlatan arrive en 2012 avec QSI. 30 buts impressionnants sous Ancelotti. Ibra : 'Quand j'arrive dans un pays, je veux être le meilleur.' Il l'est."},
    2014:{champion:"Paris Saint-Germain",coach:"Laurent Blanc",      topScorer:{name:"Zlatan Ibrahimović",goals:26},note:"Blanc remplace Ancelotti (parti à Real). Zlatan 26 buts, Cavani arrivé mais dans l'ombre de Zlatan. Matuidi-Verratti paire révolutionnaire."},
    2015:{champion:"Paris Saint-Germain",coach:"Laurent Blanc",      topScorer:{name:"Zlatan Ibrahimović",goals:38},note:"Zlatan marque 38 buts — record absolu de la Ligue 1 dans l'ère moderne ! Plus extraordinaire : il a 34 ans. Un seul joueur peut se permettre ça."},
    2016:{champion:"Paris Saint-Germain",coach:"Laurent Blanc",      topScorer:{name:"Zlatan Ibrahimović",goals:38},note:"Zlatan encore 38 buts ex-æquo avec son propre record ! Dernière saison avant Manchester United. PSG 4 titres consécutifs."},
    2017:{champion:"Monaco",             coach:"Leonardo Jardim",    topScorer:{name:"Radamel Falcao",goals:21},note:"Monaco CHAMPION à 17:1 odds ! Budget inférieur au PSG de 3:1. Falcao (retour de blessure), Mbappé (18 ans, 26 buts en buts/passes), Bernardo Silva, Mendy, Bakayoko, Fabinho. Tous vendus l'été suivant."},
    2018:{champion:"Paris Saint-Germain",coach:"Unai Emery",         topScorer:{name:"Edinson Cavani",goals:28},note:"Neymar arrive pour 222M€ record mondial en août 2017. Cavani 28 buts. PSG domine mais se fait éliminer dès les 8e de UCL vs Real (3-1)."},
    2019:{champion:"Paris Saint-Germain",coach:"Thomas Tuchel",      topScorer:{name:"Kylian Mbappé",goals:33},note:"Mbappé 33 buts à 20 ans ! Tuchel arrive. PSG invincible en L1 mais pas en UCL. 1er titre de Tuchel."},
    2020:{champion:"Paris Saint-Germain",coach:"Thomas Tuchel",      topScorer:{name:"Kylian Mbappé",goals:18},note:"Saison tronquée COVID. PSG déclaré champion mathématiquement. PSG atteint la FINALE de UCL (0-1 vs Bayern). Mbappé 18 buts en saison écourtée."},
    2021:{champion:"Lille",              coach:"Christophe Galtier", topScorer:{name:"Wissam Ben Yedder",goals:25},note:"EXPLOIT ! Lille brise 10 ans de domination PSG. Galtier (futur Nice, PSG) impeccable. Burak Yilmaz buteur-passeur clé. Renato Sanches transféré pour 15M€ à PSG l'été suivant. Ben Yedder (Monaco) meilleur buteur."},
    2022:{champion:"Paris Saint-Germain",coach:"Mauricio Pochettino", topScorer:{name:"Wissam Ben Yedder",goals:25},note:"PSG avec Messi ! Messi arrive de Barcelone pour 0€ (rupture de contrat). Mais Messi décevant en L1. Ben Yedder encore meilleur buteur malgré Monaco sans titre."},
    2023:{champion:"Paris Saint-Germain",coach:"Luis Enrique",        topScorer:{name:"Kylian Mbappé",goals:27},
          note:"Mbappé annonce son départ pour le Real Madrid à la fin de saison. Néanmoins décisif avec 27 buts. Luis Enrique transforme le PSG en équipe collective. Dernière saison de Mbappé à Paris."},
  },

  // ══════════════════════════════════════════════════════════════
  // PREMIER LEAGUE / FIRST DIVISION — depuis 1889
  // ══════════════════════════════════════════════════════════════
  39: {
    1889:{champion:"Preston North End",   note:"Preston invaincu toute la saison (22 matchs) ET gagne la FA Cup : premier Double de l'histoire du football anglais. John Goodall meilleur buteur 21 buts."},
    1890:{champion:"Preston North End",   note:"2e titre consécutif mais cette fois quelques défaites."},
    1892:{champion:"Sunderland",          topScorer:{name:"John Campbell",goals:32},note:"'L'équipe de toutes les nations' (8 nationalités). John Campbell 32 buts."},
    1898:{champion:"Sheffield United",    note:"Sheffield United — seul titre de l'histoire pour ce club."},
    1901:{champion:"Liverpool",           note:"1er titre de Liverpool, fondé seulement en 1892."},
    1907:{champion:"Newcastle United",    note:"3e titre de Newcastle. Le club ne gagnera plus la ligue depuis… 1927."},
    1908:{champion:"Manchester United",   note:"1er titre de l'histoire de Manchester United. Ernest Mangnall entraîneur."},
    1911:{champion:"Manchester United",   note:"2e titre. Billy Meredith, Sandy Turnbull."},
    1927:{champion:"Newcastle United",    note:"Dernier titre de Newcastle. Depuis 97 ans sans championnat pour les Toon Army."},
    1931:{champion:"Arsenal",             topScorer:{name:"Ted Drake",goals:39},note:"Arsenal domination de l'ère Herbert Chapman. Alex James, David Jack. Chapman invente la tactique WM."},
    1933:{champion:"Arsenal",             note:"3e titre Arsenal. Chapman décède en 1934 d'une pneumonie, son successeur finit le travail."},
    1934:{champion:"Arsenal",             note:"4e titre. Arsenal sous Joe Shaw puis George Allison."},
    1935:{champion:"Arsenal",             note:"5e titre en 7 ans — la 1ère grande domination d'un club anglais."},
    1947:{champion:"Liverpool",           coach:"George Kay",           note:"Liverpool bat Stoke City d'1 point. Dernière saison en D1 avant une longue attente."},
    1955:{champion:"Chelsea",             coach:"Ted Drake",            note:"Seul titre pré-Abramovich de Chelsea. Drake entraîneur revit. Chelsea attendrait ensuite jusqu'à 2005."},
    1956:{champion:"Manchester United",   coach:"Matt Busby",           topScorer:{name:"Dennis Viollet",goals:20},note:"Les Busby Babes ! Jeune équipe de talents. Viollet, Taylor, Duncan Edwards. Tous seront tués ou blessés lors du crash de Munich (1958)."},
    1957:{champion:"Manchester United",   coach:"Matt Busby",           note:"2e titre consécutif. La Ligue empêche Man United de participer à la Coupe d'Europe — Busby passe outre. Tragédie de Munich l'année suivante."},
    1965:{champion:"Manchester United",   coach:"Matt Busby",           note:"Busby reconstruit après Munich. Best, Law, Charlton. La trinité sacrée. 1er titre depuis 1957."},
    1967:{champion:"Manchester United",   coach:"Matt Busby",           topScorer:{name:"Ron Davies",goals:37},note:"United avec Best, Law, Charlton — Best ballon d'or. Davies (Southampton) 37 buts pour un club non champion."},
    1971:{champion:"Arsenal",             coach:"Bertie Mee",           note:"Doublé Arsenal (Ligue + FA Cup) — 1ère fois pour un club de l'ère moderne. Frank McLintock capitaine. Arsenal qui joue 'boring boring Arsenal'."},
    1975:{champion:"Derby County",        coach:"Dave Mackay",          note:"2e titre de Derby. Clough avait quitté pour Nottingham. Mackay, son ancien capitaine, prend la relève."},
    1978:{champion:"Nottingham Forest",   coach:"Brian Clough",         note:"Clough promu en D1 la saison précédente, CHAMPION dès la 1ère saison ! Avec une équipe de non-stars. Viv Anderson, Trevor Francis (1er million de £ en janvier 1979)."},
    1989:{champion:"Arsenal",             coach:"George Graham",        topScorer:{name:"Alan Smith",goals:23},note:"LA finale de championnat la plus dramatique. Arsenal vs Liverpool (1er et 2e). Arsenal doit gagner 2-0 pour être champion. Michael Thomas marque à la 91e minute ! 2-0 pour Arsenal. Commentaire de Brian Moore immortel."},
    1991:{champion:"Arsenal",             coach:"George Graham",        note:"Arsenal champion sans perdre un match en championnat — invaincu ! (Un match nul + le reste, victoires). Précurseur des Invincibles 2004."},
    1993:{champion:"Manchester United",   coach:"Alex Ferguson",        note:"1er titre Premier League (rebrand de la ligue en 1992-93). Ferguson champion pour la 1ère fois depuis 26 ans de disette de Man United."},
    1994:{champion:"Manchester United",   coach:"Alex Ferguson",        topScorer:{name:"Andy Cole",goals:34},note:"United doublé. Cantona crucial. Andy Cole (Newcastle) 34 buts — record Premier League avec 42 matchs saison."},
    1995:{champion:"Blackburn Rovers",    coach:"Kenny Dalglish",       topScorer:{name:"Alan Shearer",goals:34},note:"Shearer 34 buts record à 24 ans. Premier milliardaire à financer un club (Jack Walker). Blackburn bat Man United à la dernière journée. Le dernier titre d'un club 'modeste' avant longtemps."},
    1998:{champion:"Arsenal",             coach:"Arsène Wenger",        topScorer:{name:"Dion Dublin",goals:18},note:"DOUBLÉ Arsenal (Ligue + FA Cup). Wenger révolutionne l'entraînement, la nutrition, le recrutement étranger. Henry, Anelka, Petit, Vieira. 'Le football de Wenger' devient une référence mondiale."},
    1999:{champion:"Manchester United",   coach:"Alex Ferguson",        note:"TREBLE historique Ligue + FA Cup + UCL. Ferguson intouchable. United perd en finale FA Cup sans Keane et Scholes (suspendus). Puis bat Bayern Frankfurt en UCL avec Sheringham + Solskjaer à 90'+3."},
    2002:{champion:"Arsenal",             coach:"Arsène Wenger",        topScorer:{name:"Thierry Henry",goals:24},note:"Henry 24 buts. Wenger commence à construire les Invincibles. Arsenal perd la finale de la Champions League quelques années après mais domine la PL."},
    2003:{champion:"Arsenal",             coach:"Arsène Wenger",        topScorer:{name:"Thierry Henry",goals:30},note:"LES INVINCIBLES ! 38 matchs sans défaite. Thierry Henry 30 buts. Wenger : 'La saison parfaite'. Vieira, Pires, Bergkamp, Lehmann. Personne n'a réédité cela."},
    2004:{champion:"Chelsea",             coach:"José Mourinho",         note:"1er titre de Chelsea sous Mourinho. José Mourinho 'l'homme spécial' arrive de Porto. Drogba, Lampard, Terry. 95 points."},
    2012:{champion:"Manchester City",     coach:"Roberto Mancini",      topScorer:{name:"Robin van Persie",goals:30},note:"AGUEROOOOOOOO ! City mène Manchester United au classement. À la 93e+20, Agüero marque pour Manchester City vs QPR. City champion sur la différence de buts. Commentateur Martin Tyler : 'Agueroooooo !!!' Van Persie 30 buts pour Man United."},
    2013:{champion:"Manchester United",   coach:"Alex Ferguson",        topScorer:{name:"Robin van Persie",goals:26},note:"Dernier titre de Ferguson (né en 1941). Il annonce sa retraite à 71 ans, champion au bout. 13 titres en 27 ans. 'Sir Alex est le plus grand entraîneur de l'ère moderne' (Wenger)."},
    2016:{champion:"Leicester City",      coach:"Claudio Ranieri",      topScorer:{name:"Harry Kane",goals:25},note:"LE MIRACLE FOOTBALLISTIQUE du XXIe siècle ! Leicester à 5000-1 contre avant la saison. Vardy bat le record de buts consécutifs (11 matchs de suite). Ranieri en larmes. Tout le monde veut Leicester champion sauf Leicester lui-même (dit-il). Mahrez Joueur de l'année PFA."},
    2018:{champion:"Manchester City",     coach:"Pep Guardiola",        topScorer:{name:"Mohamed Salah",goals:32},note:"100 POINTS en championnat — record absolu ! 32 victoires. City bat tous les records. Salah (Liverpool) marque 32 buts — record partagé avec Kane. Guardiola football total au premier plan."},
    2020:{champion:"Liverpool",           coach:"Jürgen Klopp",         topScorer:{name:"Jamie Vardy",goals:23},note:"30 ans de disette ! Gerrard pleure sur le sol d'Anfield en 2014. Henderson soulève le titre 2020. Klopp : 'Ce groupe est le meilleur que j'ai jamais entraîné.' Covid — titre remis en juin sans public."},
    2023:{champion:"Manchester City",     coach:"Pep Guardiola",        topScorer:{name:"Erling Haaland",goals:36},note:"TREBLE historique City (Ligue + FA Cup + UCL). Haaland 36 buts en PL — record absolu (en 35 matchs). 52 buts en 53 matchs toutes compétitions. Guardiola dit qu'Haaland est 'alien' (en bon sens)."},
  },

  // ══════════════════════════════════════════════════════════════
  // BUNDESLIGA — depuis 1964
  // ══════════════════════════════════════════════════════════════
  78: {
    1964:{champion:"Köln",           note:"1ère Bundesliga. 16 clubs. Köln avec Hans Schäfer (joueur de la finale CdM 1954)."},
    1970:{champion:"Borussia Mönchengladbach",coach:"Hennes Weisweiler",note:"MGB commence sa domination des 70s avec Netzer et Heynckes."},
    1971:{champion:"Borussia Mönchengladbach",topScorer:{name:"Jupp Heynckes",goals:22},note:"Heynckes futur entraîneur ! 22 buts cette saison. Le 'Gladbacher' continue sa domination."},
    1972:{champion:"Bayern Munich",   coach:"Udo Lattek",  topScorer:{name:"Gerd Müller",goals:40},note:"Gerd Müller 40 buts ! Record absolu de la Bundesliga, battu 48 ans plus tard. 'Der Bomber der Nation' marque 365 buts en Bundesliga."},
    1976:{champion:"Bayern Munich",   coach:"Dettmar Cramer",note:"Triplé Bayern (74-75-76). Müller, Beckenbauer, Rummenigge. La même équipe qui gagne la CdM 1974."},
    1978:{champion:"Köln",           coach:"Hennes Weisweiler",note:"Köln 2e titre. Harald 'Toni' Schumacher gardien qui finira 3e au ballon d'or."},
    1998:{champion:"Kaiserslautern", coach:"Otto Rehhagel",note:"L'INCROYABLE ! Kaiserslautern vient d'être promu de D2. Champion dès leur retour ! Rehhagel (futur champion d'Europe avec la Grèce 2004). Miracle allemand."},
    2002:{champion:"Borussia Dortmund",coach:"Matthias Sammer",topScorer:{name:"Marcio Amoroso",goals:18},note:"Dortmund domine. Amoroso (Brésilien) meilleur buteur. Sammer ex-Ballon d'Or entraîneur."},
    2004:{champion:"Werder Bremen",  coach:"Thomas Schaaf",topScorer:{name:"Roy Makaay",goals:23},note:"Werder Bremen Champion + coupe. Johan Micoud, Ailton, Klasnic. Schaaf avec le club depuis 14 ans !"},
    2007:{champion:"VfB Stuttgart",  coach:"Armin Veh",   topScorer:{name:"Kevin Kuranyi",goals:15},note:"Stuttgart champion surprise ! Hellas Veh tactique solide. Cacau, Gomez, Hitzlsperger décisifs."},
    2009:{champion:"VfL Wolfsburg",  coach:"Felix Magath", topScorer:{name:"Edin Džeko",goals:26},note:"Wolfsburg (club de Volkswagen) CHAMPION ! Dzeko (BiH) 26 buts avec Grafite 28 — les 2 meilleurs buteurs de la saison. Magath génie tactique bref."},
    2011:{champion:"Borussia Dortmund",coach:"Jürgen Klopp",topScorer:{name:"Mario Gomez",goals:28},note:"Dortmund sous KLOPP ! 24 points d'avance sur le 2e. Götze, Reus, Kagawa, Lewandowski. La Gegenpressing révolutionne le football. Gomez (Bayern) 28 buts pour un autre club."},
    2012:{champion:"Borussia Dortmund",coach:"Jürgen Klopp",note:"DOUBLE Bundesliga + DFB Pokal. 81 points — record Bundesliga. Klopp-Dortmund au sommet. La même saison, Dortmund atteint la finale UCL (perdue vs Bayern)."},
    2013:{champion:"Bayern Munich",  coach:"Jupp Heynckes",topScorer:{name:"Robert Lewandowski",goals:24},note:"25 points d'avance sur le 2e (Dortmund) — record mondial ! Heynckes TREBLE (Bundesliga + DFB Pokal + UCL). Titre obtenu en 7 journées avant la fin. Lewandowski (Dortmund) 24 buts."},
    2020:{champion:"Bayern Munich",  coach:"Hansi Flick",  topScorer:{name:"Robert Lewandowski",goals:34},note:"Flick nommé en cours de saison après Kovač. Lewandowski 34 buts. Bayern TREBLE pendant COVID."},
    2021:{champion:"Bayern Munich",  coach:"Hansi Flick",  topScorer:{name:"Robert Lewandowski",goals:41},note:"LEWANDOWSKI 41 BUTS ! Bat le record de Gerd Müller (40 buts, 1972) à la 34e journée. Müller lui avait dit d'essayer de battre son record. Lewandowski le bat à la 90e+1 de la dernière journée. Émotion totale."},
    2022:{champion:"Bayern Munich",  coach:"Thomas Tuchel", topScorer:{name:"Christopher Nkunku",goals:18},note:"Bayern perd plusieurs matches inhabituels. Nagelsmann licencié à la surprise générale (Bayern 1er au championnat), remplacé par Tuchel (ex-Chelsea). Bayern 11e titre consécutif."},
    2023:{champion:"Bayer Leverkusen",coach:"Xabi Alonso",  note:"INVINCIBLES ! 51 matchs consécutifs sans défaite. 34V+2N en Bundesliga — 1er titre de Leverkusen. Xabi Alonso coach révélation."},
  },

  // ══════════════════════════════════════════════════════════════
  // LA LIGA — depuis 1929
  // ══════════════════════════════════════════════════════════════
  140: {
    1929:{champion:"Barcelona",    topScorer:{name:"Pitus Prat",goals:19},note:"1ère saison de Liga. 10 clubs. Barça champion inaugural."},
    1930:{champion:"Athletic Bilbao",note:"Athletic perd sa domination espagnole. Guillermo Gorostiza attaquant légendaire."},
    1935:{champion:"Real Betis",   note:"Seul et unique titre du Betis dans toute son histoire."},
    1940:{champion:"Atlético Aviación",note:"Club préfigurateur d'Atlético Madrid. Nom 'Aviación' car soutenu par l'Armée de l'Air espagnole sous Franco."},
    1960:{champion:"Barcelona",    coach:"Helenio Herrera",topScorer:{name:"Alfredo Di Stéfano",goals:25},note:"Herrera avec Barça (avant l'Inter). Di Stéfano (jouant pour le Real mais aussi comptabilisé ici) — les statistiques sont compliquées."},
    1972:{champion:"Real Madrid",  note:"Real Madrid domination sous la dictature franquiste. Santiago Bernabéu président infatigable."},
    1974:{champion:"Barcelona",    coach:"Johan Cruyff",  note:"Cruyff JOUE et est entraîneur informel. Il arrive de l'Ajax et transforme Barça. Cette saison marque le début de la philosophie Barça."},
    1985:{champion:"Barcelona",    coach:"Terry Venables", topScorer:{name:"Hugo Sánchez",goals:22},note:"Maradona à Barça (1982-84), parti maintenant à Naples. Venables (Anglais) champion. Ballon d'Or de Platini."},
    2000:{champion:"Deportivo de La Coruña",coach:"Javier Irureta",note:"COUP DE TONNERRE ! Deportivo bat le Real et le Barça. Mauro Silva, Bebeto, Bebeto passé. Fran, Roy Makaay décisifs. Budget modeste mais organisation parfaite."},
    2004:{champion:"Valencia",     coach:"Rafael Benítez", topScorer:{name:"Vicente",goals:20},note:"Valencia 2e titre en 3 ans sous Benítez. Cañizares, Marchena, Angulo, Ayala. Club méditerranéen au sommet."},
    2006:{champion:"Barcelona",    coach:"Frank Rijkaard", topScorer:{name:"Samuel Eto'o",goals:26},note:"Barça champion + UCL. Ronaldinho au sommet de son art (Ballon d'Or 2005). Eto'o 26 buts. Guardiola assistant de Rijkaard."},
    2009:{champion:"Barcelona",    coach:"Pep Guardiola",  topScorer:{name:"Diego Forlán",goals:32},note:"TREBLE HISTORIQUE Barça (Liga + Copa del Rey + UCL) ! Guardiola 1ère saison. Forlán (Atlético) 32 buts meilleur buteur mais non champion. Messi commence à éclore."},
    2012:{champion:"Real Madrid",  coach:"José Mourinho",  topScorer:{name:"Lionel Messi",goals:50},note:"MESSI 50 BUTS en une saison Liga ! Record absolu de tous les temps. Real champion avec 100 points — record historique. Mais Messi perd le titre avec Barça."},
    2014:{champion:"Atlético Madrid",coach:"Diego Simeone",topScorer:{name:"Diego Costa",goals:27},note:"Simeone CHAMPION avec l'Atlético ! Diego Costa 27 buts avant son transfert à Chelsea. Courtois gardien. Atlético bat Real ET Barça. Mourinho part après 3 ans et des relations tendues."},
    2017:{champion:"Barcelona",    coach:"Ernesto Valverde",topScorer:{name:"Lionel Messi",goals:34},note:"Barcelone record 93 points. Messi 34 buts. Seule défaite vs Real Betis (0-1)."},
    2021:{champion:"Atlético Madrid",coach:"Diego Simeone",topScorer:{name:"Lionel Messi",goals:30},note:"Atlético champion à la dernière journée ! Simeone brise la domination Barça-Real. Messi 30 buts mais quitte le Barça cet été (rupture financière du club)."},
    2022:{champion:"Barcelona",    coach:"Xavi Hernández",  topScorer:{name:"Robert Lewandowski",goals:23},note:"1er titre de l'ère post-Messi. Lewandowski 23 buts. Xavi champion dès sa 1ère saison complète."},
    2023:{champion:"Real Madrid",  coach:"Carlo Ancelotti",  note:"Real champion avec Bellingham décisif (22 buts dont beaucoup en fin de match). Vinicius, Rodrygo, Modric encore là."},
  },

  // ══════════════════════════════════════════════════════════════
  // SERIE A — depuis 1929
  // ══════════════════════════════════════════════════════════════
  135: {
    1949:{champion:"Torino",       note:"Le championnat de 1948-49 attribué à Torino en hommage aux joueurs morts dans le crash aérien de la Basilique de Superga (4 mai 1949). Toute l'équipe décède."},
    1985:{champion:"Verona",       note:"Hellas Verona champion de toute l'Italie ! Seul et unique titre. Briegel, Elkjær-Larsen (danois), Di Gennaro. Entraîneur Osvaldo Bagnoli. Budget inférieur à la Juve et l'Inter."},
    1987:{champion:"Napoli",       coach:"Ottavio Bianchi",topScorer:{name:"Diego Maradona",goals:15},note:"1ER TITRE DE NAPOLI grâce à Maradona ! 60 000 personnes sur la Piazza del Plebiscito. 'Je suis sûr que les pauvres gens ont enfin eu leur revanche' dit Maradona. Naples pleure de joie."},
    1990:{champion:"Napoli",       coach:"Alberto Bigon",  topScorer:{name:"Marco van Basten",goals:19},note:"2e titre pour Napoli. Maradona encore là. Van Basten (Milan) 19 buts pour un autre club. Maradona sera contrôlé positif à la cocaïne en 1991 et suspendu 15 mois."},
    1994:{champion:"AC Milan",     coach:"Fabio Capello",  topScorer:{name:"Giuseppe Signori",goals:23},note:"Milan de Capello champion invaincu ! 0 défaite en Serie A. Baresi, Maldini, Costacurta derrière ; Boban, Albertini, Savicević devant."},
    2006:{champion:"Inter Milan",  note:"Titre attribué à Inter par défaut après retrait à Juventus (Calciopoli)."},
    2007:{champion:"Inter Milan",  coach:"Roberto Mancini", topScorer:{name:"Francesco Totti",goals:26},note:"Totti (Roma) 26 buts — meilleur buteur mais pas champion. Mancini bâtit l'Inter solide."},
    2010:{champion:"Inter Milan",  coach:"José Mourinho",  topScorer:{name:"Antonio Di Natale",goals:29},note:"TREBLE HISTORIQUE d'Inter sous Mourinho ! Di Natale (Udinese) 29 buts. Mourinho après la UCL (victoire vs Bayern) court le stade Bernabéu les bras en croix — nommé entraîneur du Real l'été suivant."},
    2019:{champion:"Juventus",     coach:"Massimiliano Allegri",topScorer:{name:"Fabio Quagliarella",goals:26},note:"9e titre consécutif de Juve ! Quagliarella (Sampdoria, 36 ans) meilleur buteur à 36 ans — record de vétérance."},
    2023:{champion:"Napoli",       coach:"Luciano Spalletti",topScorer:{name:"Victor Osimhen",goals:26},note:"1er titre de Napoli depuis Maradona (1990) — 33 ANS D'ATTENTE ! Osimhen (Nigeria) 26 buts. Khvicha Kvaratskhelia révélation absolue. Spalletti quitte le club après le titre pour devenir sélectionneur de l'Italie. Naples en fête totale."},
  },

  // ══════════════════════════════════════════════════════════════
  // COPA AMÉRICA — depuis 1916
  // ══════════════════════════════════════════════════════════════
  9: {
    1916:{champion:"Uruguay",  note:"1ère Copa América, appelée 'Campeonato Sudamericano de Football'. Organisée à Buenos Aires pour le centenaire de l'indépendance argentine."},
    1950:{champion:"Uruguay",  note:"La même année que le Maracanazo. Uruguay sur le toit du monde."},
    1993:{champion:"Argentina",note:"Messi avait 5 ans. Batistuta 5 buts. Caniggia, Balbo. Argentina bat Mexique 2-1 en finale."},
    2001:{champion:"Colombia", note:"Seul titre de la Colombie ! Carlos Bacca et Juan Carlos Osorio pas encore là mais inspirés par cette victoire. Carlos Valderrama (37 ans !) dans la sélection."},
    2004:{champion:"Brazil",   coach:"Carlos Alberto Parreira",topScorer:{name:"Adriano",goals:7},note:"Adriano surnommé 'l'Imperatore' marque 7 buts. Ronaldinho, Kaká, Ronaldo dans l'équipe. Le Brésil de transition vers la génération 2006."},
    2007:{champion:"Brazil",   coach:"Dunga",topScorer:{name:"Robinho",goals:6},note:"Robinho 6 buts. Brésil championne avec Dunga (défensif) qui réhabilite le jeu pragmatique. Messi présent mais Barça gagne."},
    2011:{champion:"Uruguay",  coach:"Óscar Tabárez",topScorer:{name:"Paolo Guerrero",goals:5},note:"Uruguay à 40 ans du dernier titre ! Forlan, Suárez, Cavani : la meilleure attaque. Tabárez 'El Maestro' transforme l'Uruguay."},
    2015:{champion:"Chile",    coach:"Jorge Sampaoli",topScorer:{name:"Eduardo Vargas",goals:6},note:"1er titre du Chili de TOUS LES TEMPS ! Vargas 6 buts. Vidal, Sánchez, Medel. Sampaoli football offensif total. Chili bat Argentine aux tirs au but."},
    2016:{champion:"Chile",    coach:"Juan Antonio Pizzi",note:"Copa Centenario (100 ans) aux USA. Chili champion à nouveau vs Argentine (encore). Brésil et Messi non invités. Messi annonce sa retraite internationale… avant de revenir."},
    2019:{champion:"Brazil",   coach:"Tite",topScorer:{name:"Éverton",goals:3},note:"Brésil champion à domicile. Éverton (Grêmio) révélation. Jesus, Firmino. Messi suspendu pour avoir accusé la CONMEBOL de corruption après la demi-finale."},
    2021:{champion:"Argentina",coach:"Lionel Scaloni",topScorer:{name:"Lionel Messi",goals:4},note:"ENFIN ! 1er titre de Messi en sélection ! Argentina bat Brésil 1-0 en finale au Maracanã. Di María marque. Messi pleure. 28 ans après le dernier titre argentin (1993)."},
  },

  // ══════════════════════════════════════════════════════════════
  // UEFA EURO — depuis 1960
  // ══════════════════════════════════════════════════════════════
  4: {
    1960:{champion:"Soviet Union",  host:"France",        topScorer:{name:"Slava Metreveli",goals:2},note:"1ère édition, seulement 4 équipes. URSS bat Yougoslavie 2-1 ap. 17 000 spectateurs au Parc des Princes — les JO avaient plus de monde !"},
    1964:{champion:"Spain",         host:"Espagne",       topScorer:{name:"Jesus Pereda",goals:2},note:"Espagne bat URSS 2-1. Franco a refusé de jouer contre l'URSS en 1960, cette fois il accepte. Luis Suárez (Interiste) décisif."},
    1968:{champion:"Italy",         host:"Italie",        note:"Demi-finale France vs Yougoslavie — résultat déterminé au pile ou face ! Italie bat Yougoslavie en finale replay 2-0. Le seul titre de l'Italie à l'Euro."},
    1972:{champion:"West Germany",  host:"Belgique",      topScorer:{name:"Gerd Müller",goals:4},note:"Müller 4 buts. Beckenbauer-Müller-Breitner-Netzer. Allemagne 3-0 vs URSS en finale. Préfigure la CdM 1974."},
    1976:{champion:"Czechoslovakia",host:"Yougoslavie",   note:"Tchecoslovaquie bat Allemagne aux tirs au but. Uli Hoeness (futur président Bayern) rate son penalty. Panenka INVENTE la Panenka : tir en cuillère lent au centre. 'Jamais je ne l'aurais tenté en CdM' dit-il."},
    1980:{champion:"West Germany",  host:"Italie",        topScorer:{name:"Klaus Allofs",goals:3},note:"Premier Euro à 8 équipes. L'Allemagne bat Belgique 2-1. Hrubesch marque 2 buts dont le dernier minute."},
    1984:{champion:"France",        host:"France",        coach:"Michel Hidalgo",topScorer:{name:"Michel Platini",goals:9},note:"PLATINI 9 BUTS EN 5 MATCHS — record absolu de l'Euro encore imbattu ! France bat Espagne 2-0 en finale. Tigana, Giresse, Fernández. 'Le carré magique'. Platini marque en demi (92e minute) et en finale."},
    1988:{champion:"Netherlands",   host:"Allemagne",     coach:"Rinus Michels",topScorer:{name:"Marco van Basten",goals:5},note:"LE BIG VAN BASTEN. Son volée en finale vs URSS du coin de la surface à angle fermé : peut-être le plus beau but de l'Euro. 2-0. Gullit ouvre le score de la tête après corner de Van Basten."},
    1992:{champion:"Denmark",       host:"Suède",         note:"MIRACLE DANOIS ! Danemark non qualifié au départ, invité 11 jours avant car Yougoslavie exclue (guerre). Joueurs rappelés de vacances. Bat les Pays-Bas en demi. Bat l'Allemagne en finale 2-0. Schmeichel monumental. Peter Schmeichel : 'Impossible à croire'."},
    1996:{champion:"Germany",       host:"Angleterre",    topScorer:{name:"Alan Shearer",goals:5},note:"Golden Goal — 1ère compétition avec règle de l'or. Bierhoff marque après la règle golden goal vs Rép. Tchèque. Shearer 5 buts, meilleur Anglais. Allemagne bat France et Angleterre (pen)."},
    2000:{champion:"France",        host:"Belgique/Pays-Bas",coach:"Roger Lemerre",topScorer:{name:"Patrick Kluivert",goals:5},note:"GOLDEN GOAL de Trezeguet vs Italie en finale ! France mène 1-0, Italie égalise à la 94e (Wiltord), puis Trezeguet marque le golden goal à la 103e. France champion du Monde 1998 ET champion d'Europe."},
    2004:{champion:"Greece",        host:"Portugal",      coach:"Otto Rehhagel",topScorer:{name:"Milan Baroš",goals:5},note:"GRÈCE CHAMPION ! Otto Rehhagel (Grec d'adoption) bat le Portugal de Figo et Ronaldo EN OUVERTURE et EN FINALE. Les bookmakers donnaient la Grèce 100-1 au début. Charisteas marque le seul but de la finale."},
    2008:{champion:"Spain",         host:"Autriche/Suisse",coach:"Luis Aragonés",topScorer:{name:"David Villa",goals:4},note:"L'Espagne du tiki-taka commence ici ! Aragonés sort Raúl — scandale en Espagne. Villa 4 buts. Torres marque le seul but de la finale vs Allemagne. Xavi meilleur joueur."},
    2012:{champion:"Spain",         host:"Ukraine/Pologne",coach:"Vicente del Bosque",topScorer:{name:"Fernando Torres",goals:3},note:"Espagne 3e trophée consécutif (Euro 08 + CdM 10 + Euro 12) ! Torres marque en finale 4-0 vs Italie. Jordi Alba contre-attaque mémorable sur la 2e de Torres. Iniesta encore décisif."},
    2016:{champion:"Portugal",      host:"France",        coach:"Fernando Santos",topScorer:{name:"Antoine Griezmann",goals:6},note:"Ronaldo BLESSÉ dès la 25e minute de la finale vs France. Il coache depuis la touche ! Eder marque à la 109e minute. Griezmann 6 buts meilleur buteur mais perd. Ronaldo pleure lors de la victoire."},
    2021:{champion:"Italy",         host:"Pan-européen",  coach:"Roberto Mancini",topScorer:{name:"Cristiano Ronaldo",goals:5},note:"53 ANS d'attente pour l'Italie ! Mancini transforme l'Italie après leur non-qualification CdM 2018. Donnarumma pareil arrête les pénaltys anglais à Wembley. Maguire, Rashford, Sancho ratent. Chiellini légende à 36 ans."},
  },

  // ══════════════════════════════════════════════════════════════
  // CAN / AFCON — depuis 1957
  // ══════════════════════════════════════════════════════════════
  6: {
    1957:{champion:"Egypt",   host:"Soudan",   note:"1ère CAN. 3 équipes seulement (Éthiopie, Soudan, Égypte). Égypte bat Éthiopie 4-0 en finale. Mohamed Diab Al-Attar meilleur buteur."},
    1968:{champion:"Congo-Kinshasa",host:"Éthiopie",note:"Après l'indépendance : République Démocratique du Congo (alors 'Congo-Kinshasa'). Mbungu marque les buts décisifs."},
    1974:{champion:"Zaire",   host:"Égypte",   note:"Zaïre de Mobutu, financé personnellement par le dictateur. Même sélection qui ira à la CdM 1974 et sera ridiculisée (9-0 vs Yougoslavie)."},
    1984:{champion:"Cameroon",coach:"Claude Le Roy",note:"Cameroun avec Roger Milla (32 ans). Le Roy, Français entraîneur d'une équipe africaine — pionnier."},
    1990:{champion:"Algeria", host:"Algérie",  note:"Algérie champion à domicile. Rabah Madjer, héros de Porto 1987, joue sa dernière grande compétition."},
    1992:{champion:"Ivory Coast",host:"Sénégal",note:"Côte d'Ivoire aux tirs au but vs Ghana. 1er titre ivoirien. Youssouf Fofana héros national."},
    1994:{champion:"Nigeria", host:"Tunisie",  note:"Super Eagles avec Emmanuel Amunike, Rashidi Yekini. Finala Nigeria bat Zambie 2-1."},
    2008:{champion:"Egypt",   host:"Ghana",    coach:"Hassan Shehata",topScorer:{name:"Mohamed Zidan",goals:5},note:"Zidan (né en Allemagne) 5 buts. 3e titre consécutif de l'Égypte en CAN — record absolu. Aboutrika, Zaki, Zidan : belle génération."},
    2010:{champion:"Egypt",   host:"Angola",   coach:"Hassan Shehata",topScorer:{name:"Mohamed Gedo",goals:5},note:"7e titre de l'Égypte — RECORD ABSOLU de l'histoire de la CAN (7 titres). Gedo 5 buts. Aboutrika décisif. L'Égypte champion d'Afrique pour la 3e fois consécutive."},
    2012:{champion:"Zambia",  host:"Gabon/Guinée Équatoriale",topScorer:{name:"Pierre-Emerick Aubameyang",goals:2},note:"MIRACLE DE LA ZAMBIE ! Bat la Côte d'Ivoire de Drogba aux tirs au but. Tragique : l'équipe renommée honore les 18 joueurs zambiens morts dans un crash aérien EN 1993 au large de Libreville (Gabon). Finans — Zambie champion sur les mêmes lieux !"},
    2013:{champion:"Nigeria", host:"Afrique du Sud",topScorer:{name:"Emmanuel Emenike",goals:4},note:"Stephen Keshi est le 2e homme à gagner la CAN comme joueur ET entraîneur. Sunday Mba buteur décisif en demi et finale."},
    2015:{champion:"Ivory Coast",host:"Guinée Équatoriale",note:"Côte d'Ivoire bat Ghana aux tirs au but. Drogba (37 ans) joue sa dernière CAN. Gervinho, Toure frères décisifs."},
    2017:{champion:"Cameroon",coach:"Hugo Broos",note:"Broos (Belge) : 'Je ne connaissais pas le football africain avant.' Cameroun vs Égypte 2-1 en finale. Vincent Aboubakar marque à la 88e minute."},
    2019:{champion:"Algeria", host:"Égypte",   coach:"Djamel Belmadi",topScorer:{name:"Odion Ighalo",goals:5},note:"Mahrez marque un coup franc exceptionnel en demi vs Nigeria. Riyad Mahrez captain. L'Algérie quasi-invincible avec 29 matchs sans défaite après. Belmadi coach révélation."},
    2021:{champion:"Senegal", host:"Cameroun", coach:"Aliou Cissé",    topScorer:{name:"Vincent Aboubakar",goals:8},note:"1ER TITRE DU SÉNÉGAL ! Aboubakar (Cameroun, organisateur) 8 buts dont 5 dans son camp pratiquement… non, pour le Cameroun. Sénégal bat Égypte aux tirs au but. Sadio Mané marque le tir au but décisif. Cissé pleure."},
    2023:{champion:"Ivory Coast",host:"Côte d'Ivoire",note:"CIV organisateur ET champion ! Commencent la CAN avec des résultats catastrophiques, risquent l'élimination au 1er tour, puis enchaînent 6 victoires. Battent le Nigeria 2-1 en finale. Emerse Faé nommé entraîneur en cours de tournoi."},
  },

  // ══════════════════════════════════════════════════════════════
  // COPA LIBERTADORES — depuis 1960
  // ══════════════════════════════════════════════════════════════
  11: {
    1960:{champion:"Peñarol",  note:"1ère Libertadores. Peñarol (Uruguay) bat Olimpia 1-0. Peñarol dominant de la 1ère décennie."},
    1962:{champion:"Santos",   note:"Pelé avec Santos. 2 titres consécutifs. Les matchs de gala contre le Real Madrid ont popularisé le football brésilien en Europe."},
    1963:{champion:"Santos",   note:"2e consécutif. Pelé à son sommet. Santos bat Boca Juniors."},
    1981:{champion:"Flamengo", coach:"Cláudio Coutinho",note:"1er titre de Flamengo. Zico 'O Galinho' décisif. Flamengo bat Cobreloa 3-0 en finale retour après 2-1 à l'aller."},
    1985:{champion:"Argentinos Juniors",note:"Club de Buenos Aires (club formateur de Maradona 1976-1981). Premier et unique titre. Batent América de Cali aux tirs au but."},
    1989:{champion:"Atlético Nacional",note:"1er titre colombien. Faustino Asprilla jeune, Andrés Escobar décisif. René Higuita gardien acrobatique. Colombie en plein boom du narcotrafic — contexte sombre."},
    2000:{champion:"Boca Juniors",note:"Boca avec Juan Román Riquelme. Finale vs Palmeiras. La época de oro de Boca commence."},
    2001:{champion:"Boca Juniors",note:"2e consécutif. Riquelme roi. Boca vs Cruz Azul. Ce Boca gagnera 4 Libertadores en 5 ans (2000-2001-2003-2007)."},
    2003:{champion:"Boca Juniors",note:"3e Libertadores. Carlos Tevez, Riquelme. Boca Juniors le club le plus titré (8 Libertadores). Finale vs Santos."},
    2018:{champion:"River Plate", note:"LA FINALE DE TOUS LES DANGERS ! Super Clásico en finale : River Plate vs Boca Juniors — 1ère fois les deux rivaux en finale de Libertadores. Délocalisée au Bernabéu (Madrid) après incidents. River bat Boca 3-1 ap. Quintero marque à 90'+8 le but d'égalisation !"},
    2019:{champion:"Flamengo",  coach:"Jorge Jesus",topScorer:{name:"Gabriel Barbosa (Gabigol)",goals:6},note:"Jorge Jesus transforme Flamengo. Gabigol 2 buts décisifs en finale vs River Plate (2-1) dans les arrêts de jeu. 38 ans depuis le dernier titre. Rio de Janeiro en fête."},
    2021:{champion:"Palmeiras", coach:"Abel Ferreira",topScorer:{name:"Luís Díaz",goals:8},note:"Abel Ferreira (Portugais) champion avec Palmeiras. Luís Díaz (Colombia, futur Liverpool) 8 buts. Palmeiras bat Flamengo — Derby brésilien en finale."},
    2023:{champion:"Fluminense", coach:"Fernando Diniz",topScorer:{name:"Germán Cano",goals:11},note:"Fluminense 1er titre ! Diniz et son jogo bonito. Cano 11 buts. Finale au Maracanã (stade de Fluminense). Nino (défenseur) héros. Marcelo (ancien Real Madrid) joue sa dernière grande compétition."},
  },

  // ══════════════════════════════════════════════════════════════
  // UEFA NATIONS LEAGUE — depuis 2018
  // ══════════════════════════════════════════════════════════════
  5: {
    2019:{champion:"Portugal",  coach:"Fernando Santos",topScorer:{name:"Cristiano Ronaldo",goals:6},note:"1ère édition, organisée au Portugal. Guedes marque le seul but en finale vs Pays-Bas. Portugal organisateur et champion, comme à l'Euro 2004 (où ils avaient perdu)."},
    2021:{champion:"France",    coach:"Didier Deschamps",topScorer:{name:"Kylian Mbappé",goals:4},note:"France bat Espagne 2-1 en finale à Milan. Mbappé marque. Benzema revient en équipe de France après 5 ans d'absence — décisif en demi vs Belgique (3-2 remontée depuis 0-2)."},
    2023:{champion:"Spain",     coach:"Luis de la Fuente",topScorer:{name:"Álvaro Morata",goals:4},note:"Espagne de la nouvelle génération : Gavi, Pedri, Yamal (16 ans !), Williams. Bat la Croatie 5-4 ap en demi — match fou. Olmo marque le but décisif en finale vs Croatie. Préfigure l'Euro 2024 (qu'ils gagneront aussi)."},
  },

  // ══════════════════════════════════════════════════════════════
  // UEFA EUROPA LEAGUE — depuis 1972 (ancienne Coupe UEFA)
  // ══════════════════════════════════════════════════════════════
  3: {
    1972:{champion:"Tottenham",  coach:"Bill Nicholson",topScorer:{name:"Alan Mullery",goals:3},note:"1ère Coupe UEFA. Tottenham bat Wolverhampton 3-2 total. Greaves avait quitté le club en 1970."},
    1973:{champion:"Liverpool",  coach:"Bill Shankly",   note:"Shankly gagne sa dernière compétition européenne. Il démissionne mystérieusement l'été suivant, sans raison claire."},
    1989:{champion:"Napoli",     coach:"Ottavio Bianchi",topScorer:{name:"Diego Maradona",goals:5},note:"Maradona joue ET gagne la Coupe UEFA ! Napoli bat Stuttgart 5-4 total. Maradona décisif."},
    2006:{champion:"Sevilla",    coach:"Juande Ramos",   topScorer:{name:"Luís Fabiano",goals:6},note:"1er titre de Sevilla. Fabiano 6 buts. Ramos transforme Sevilla en spécialiste de l'Europa."},
    2007:{champion:"Sevilla",    coach:"Juande Ramos",   topScorer:{name:"Luis García",goals:4},note:"2e titre consécutif ! Sevilla devient le 1er club à remporter 2 Europa consécutives."},
    2010:{champion:"Atletico Madrid",coach:"Diego Simeone",note:"Simeone n'était pas encore là — en fait Diego Forlán meilleur joueur. Quique Sánchez Flores entraîneur. Forlán marque 2 fois en finale vs Fulham."},
    2014:{champion:"Sevilla",    coach:"Unai Emery",     topScorer:{name:"Kevin Gameiro",goals:5},note:"3e titre de Sevilla ! Emery commence sa saga Europa League."},
    2015:{champion:"Sevilla",    coach:"Unai Emery",     topScorer:{name:"Kevin Gameiro",goals:7},note:"4e titre (3e consécutif pour Emery) ! Gameiro 7 buts. Sevilla bat Dnipro Dnipropetrovsk."},
    2016:{champion:"Sevilla",    coach:"Unai Emery",     topScorer:{name:"Kevin Gameiro",goals:5},note:"5e titre !! EMERY 3 Europa consécutives — INÉDIT. Il sera nommé à PSG puis Arsenal ensuite."},
    2019:{champion:"Chelsea",    coach:"Maurizio Sarri",  topScorer:{name:"Olivier Giroud",goals:11},note:"Giroud 11 buts tout en ne jouant presque jamais en Premier League ! Finale entre Chelsea et Arsenal — Derby de Londres. Hazard marque 2 fois. Sa dernière saison avant Real Madrid."},
    2020:{champion:"Sevilla",    coach:"Julen Lopetegui",topScorer:{name:"Dries Mertens",goals:5},note:"6e titre de Sevilla — record absolu ! Lopetegui relancé après avoir été viré de l'équipe nationale espagnole et du Real Madrid. En-Nesyri-Ocampos. Finale vs Inter Milan 3-2."},
    2021:{champion:"Villarreal", coach:"Unai Emery",     topScorer:{name:"Dávid Hancko",goals:4},note:"Emery GAGNE ENCORE avec un 4e club différent ! Villarreal (club modeste de 50 000 habitants) bat Manchester United aux tirs au but. De Gea rate le dernier penalty. Emery : 'Je vis pour les finales'."},
    2023:{champion:"Sevilla",    coach:"José Luis Mendilibar",topScorer:{name:"Mikel Oyarzabal",goals:6},note:"7e TITRE de Sevilla — record mondial absolu ! Mendilibar nommé 3 mois avant, en catastrophe. Sevilla bat Roma de Mourinho 4-1 aux tirs au but après 1-1. Ramos (de retour à Sevilla) pleure."},
  },

  // ══════════════════════════════════════════════════════════════
  // UEFA CONFERENCE LEAGUE — depuis 2021
  // ══════════════════════════════════════════════════════════════
  848: {
    2022:{champion:"Roma",      coach:"José Mourinho",topScorer:{name:"Tammy Abraham",goals:7},note:"Mourinho gagne les 3 compétitions UEFA différentes — seul entraîneur de l'histoire ! UEFA Cup (Porto 2003) + UCL (Inter 2010) + Europa (Man United 2017) + Conference (Roma 2022). Abraham 7 buts. Roma bat Feyenoord 1-0. La ville de Rome en liesse."},
    2023:{champion:"West Ham",  coach:"David Moyes",  topScorer:{name:"Gianluca Scamacca",goals:7},note:"West Ham champion d'Europe — le premier titre européen du club ! Scamacca (Roma prêté à West Ham) 7 buts. Coufal, Areola, Bowen décisifs."},
  },

  // ══════════════════════════════════════════════════════════════
  // CLUB WORLD CUP — depuis 2000
  // ══════════════════════════════════════════════════════════════
  22: {
    2000:{champion:"Corinthians",  note:"1ère édition avec le nouveau format. Corinthians bat Vasco da Gama en finale. 73 000 spectateurs au Maracanã."},
    2005:{champion:"São Paulo",    note:"São Paulo bat Liverpool (champion UCL 2005 !) en finale 1-0 via Mineiro. Preuve que l'Amérique du Sud a le niveau UCL."},
    2006:{champion:"Internacional",note:"Inter (Porto Alegre) bat Barça 1-0 (Adriano). Immense surprise."},
    2014:{champion:"Real Madrid",  note:"1er titre Real. Après avoir gagné la UCL, domine le monde."},
    2022:{champion:"Real Madrid",  note:"6e titre Real — plus titré du monde. Vinicius et Benzema décisifs."},
  },

  // ══════════════════════════════════════════════════════════════
  // COUPE DE FRANCE — depuis 1917
  // ══════════════════════════════════════════════════════════════
  65: {
    1918:{champion:"Olympique de Paris",note:"1ère édition. Club disparu depuis."},
    1982:{champion:"Paris Saint-Germain",note:"1er titre du PSG — en Coupe de France avant leur 1er titre de championnat (1986)."},
    2011:{champion:"Lille",              note:"Doublé Lille (Ligue 1 + Coupe). Double unique pour ce club."},
    2018:{champion:"Paris Saint-Germain",note:"PSG bat Les Herbiers (D3 !) en finale 2-0. Les Herbiers, club amateur, réalise le parcours le plus surprenant de l'histoire récente mais perd la finale."},
    2022:{champion:"Nantes",             coach:"Antoine Kombouaré",topScorer:{name:"Ludovic Blas",goals:3},note:"1er titre de Nantes en 33 ans. Kombouaré reprend le club in extremis. Blas, Simon décisifs. Nantes bat Nice en finale."},
    2023:{champion:"Toulouse",           note:"1er titre de l'histoire de Toulouse ! Toulouse bat Nantes 5-1. Thijs Dallinga 2 buts. Club revenu de D2 récemment."},
  },

  // ══════════════════════════════════════════════════════════════
  // FA CUP — depuis 1872
  // ══════════════════════════════════════════════════════════════
  45: {
    1872:{champion:"Wanderers",       note:"1ère FA Cup. 15 clubs participants. Wanderers bat Royal Engineers 1-0. Le trophée est toujours le même (la coupe originale)."},
    1927:{champion:"Cardiff City",    note:"Seul club non anglais à avoir gagné la FA Cup ! Cardiff (Pays de Galles) bat Arsenal 1-0. Ferguson n'a pas encore joué."},
    1953:{champion:"Blackpool",       note:"'La Finale de Matthews'. Stan Matthews (38 ans) joue son dernier FA Cup. Blackpool revient de 3-1 à 4-3 en faveur de Blackpool. Mortensen marque un hat-trick."},
    2013:{champion:"Wigan Athletic",  note:"Wigan relégué de Premier League le même soir. Champion de FA Cup et relégué en même temps ! Ben Watson marque contre Man City à la 91e."},
    2023:{champion:"Manchester City", note:"Man City complète le TREBLE PL + FA Cup + UCL. Ilkay Gündogan marque un but après 13 secondes — le plus rapide de l'histoire d'une finale de FA Cup."},
  },

  // ══════════════════════════════════════════════════════════════
  // DFB POKAL — depuis 1935
  // ══════════════════════════════════════════════════════════════
  81: {
    1935:{champion:"Nürnberg",        note:"1ère édition. Nürnberg club populaire qui avait remporté 8 championnats dans les années 20."},
    2023:{champion:"RB Leipzig",      coach:"Marco Rose",note:"2e titre de RB Leipzig. Marco Rose entraîneur. Considéré club 'plastique' par les fans mais joueurs talentueux : Nkunku, Werner, Szoboszlai."},
  },
};
